
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Project7
{

using System;
    using System.Collections.Generic;
    
public partial class buffet_menu_items
{

    public int ids { get; set; }

    public Nullable<int> buffet_menu_id { get; set; }

    public Nullable<int> menu_item_id { get; set; }



    public virtual buffet_menus buffet_menus { get; set; }

    public virtual Product Product { get; set; }

}

}
