
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Project7
{

using System;
    using System.Collections.Generic;
    
public partial class comment
{

    public int id { get; set; }

    public string user_id { get; set; }

    public string comment1 { get; set; }

    public Nullable<int> flag { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

}

}
