

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Project7
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class project7Entities : DbContext
{
    public project7Entities()
        : base("name=project7Entities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<buffet_menu_items> buffet_menu_items { get; set; }

    public virtual DbSet<buffet_menus> buffet_menus { get; set; }

    public virtual DbSet<Category> Categorys { get; set; }

    public virtual DbSet<comment> comments { get; set; }

    public virtual DbSet<Date> Dates { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Reservation> Reservations { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

    public virtual DbSet<Table> Tables { get; set; }

    public virtual DbSet<Time> Times { get; set; }

}

}

